# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 07:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='/static/', verbose_name='Zdjęcie')),
                ('name', models.CharField(max_length=64, verbose_name='Imię')),
                ('gender', models.IntegerField(choices=[(1, 'male'), (2, 'female')], verbose_name='Płeć')),
                ('year_of_birth', models.IntegerField(verbose_name='Rok urodzenia')),
                ('breed', models.CharField(max_length=64, verbose_name='rasa')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pies',
                'verbose_name_plural': 'Psy',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voivodeship', models.IntegerField(choices=[(1, 'woj. dolnośląskie'), (2, 'woj. kujawsko-pomorskie'), (3, 'woj. lubelskie'), (4, 'woj. lubuskie'), (5, 'woj. łódzkie'), (6, 'woj. małopolskie'), (7, 'woj. mazowieckie'), (8, 'woj. opolskie'), (9, 'woj. podkarpackie'), (10, 'woj. podlaskie'), (11, 'woj. pomorskie'), (12, 'woj. śląskie'), (13, 'woj. świętokrzyskie'), (14, 'woj. warmińsko-mazurskie'), (15, 'woj. wielkopolskie'), (16, 'woj. zachodniopomorskie')])),
                ('city', models.CharField(max_length=64)),
                ('fav_walking_place', models.TextField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil użytkownika',
                'verbose_name_plural': 'Profile użytkowników',
            },
        ),
        migrations.CreateModel(
            name='Walk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voivodeship', models.IntegerField(choices=[(1, 'woj. dolnośląskie'), (2, 'woj. kujawsko-pomorskie'), (3, 'woj. lubelskie'), (4, 'woj. lubuskie'), (5, 'woj. łódzkie'), (6, 'woj. małopolskie'), (7, 'woj. mazowieckie'), (8, 'woj. opolskie'), (9, 'woj. podkarpackie'), (10, 'woj. podlaskie'), (11, 'woj. pomorskie'), (12, 'woj. śląskie'), (13, 'woj. świętokrzyskie'), (14, 'woj. warmińsko-mazurskie'), (15, 'woj. wielkopolskie'), (16, 'woj. zachodniopomorskie')], verbose_name='Województwo')),
                ('city', models.CharField(max_length=64, verbose_name='Miasto')),
                ('date_start', models.DateTimeField(verbose_name='Początek spaceru')),
                ('date_stop', models.DateTimeField(verbose_name='Koniec spaceru')),
                ('dog', models.ManyToManyField(to='walk_a_dog.Dog')),
            ],
            options={
                'verbose_name': 'Spacer',
                'verbose_name_plural': 'Spacery',
            },
        ),
    ]
