# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walk_a_dog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fav_walking_place',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='voivodeship',
            field=models.IntegerField(choices=[(0, 'wybierz województwo'), (1, 'woj. dolnośląskie'), (2, 'woj. kujawsko-pomorskie'), (3, 'woj. lubelskie'), (4, 'woj. lubuskie'), (5, 'woj. łódzkie'), (6, 'woj. małopolskie'), (7, 'woj. mazowieckie'), (8, 'woj. opolskie'), (9, 'woj. podkarpackie'), (10, 'woj. podlaskie'), (11, 'woj. pomorskie'), (12, 'woj. śląskie'), (13, 'woj. świętokrzyskie'), (14, 'woj. warmińsko-mazurskie'), (15, 'woj. wielkopolskie'), (16, 'woj. zachodniopomorskie')], default=0),
        ),
        migrations.AlterField(
            model_name='walk',
            name='voivodeship',
            field=models.IntegerField(choices=[(0, 'wybierz województwo'), (1, 'woj. dolnośląskie'), (2, 'woj. kujawsko-pomorskie'), (3, 'woj. lubelskie'), (4, 'woj. lubuskie'), (5, 'woj. łódzkie'), (6, 'woj. małopolskie'), (7, 'woj. mazowieckie'), (8, 'woj. opolskie'), (9, 'woj. podkarpackie'), (10, 'woj. podlaskie'), (11, 'woj. pomorskie'), (12, 'woj. śląskie'), (13, 'woj. świętokrzyskie'), (14, 'woj. warmińsko-mazurskie'), (15, 'woj. wielkopolskie'), (16, 'woj. zachodniopomorskie')], verbose_name='Województwo'),
        ),
    ]
