# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walk_a_dog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dog',
            options={'verbose_name': 'Pies', 'verbose_name_plural': 'Psy'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Profil użytkownika', 'verbose_name_plural': 'Profile użytkowników'},
        ),
        migrations.AlterModelOptions(
            name='walk',
            options={'verbose_name': 'Spacer', 'verbose_name_plural': 'Spacery'},
        ),
        migrations.AlterField(
            model_name='dog',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
