# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walk_a_dog', '0002_auto_20170404_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
    ]
