# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 08:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walk_a_dog', '0002_auto_20170405_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.IntegerField(choices=[(1, 'pies'), (2, 'suka')], verbose_name='Płeć'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
