# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 09:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walk_a_dog', '0004_walk_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='walk_a_dog/static/', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(max_length=64, verbose_name='Rasa'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Właściciel'),
        ),
    ]
